# Generated by Django 4.2.14 on 2025-10-26 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='variety',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='routerate',
            old_name='variety',
            new_name='supplier',
        ),
        migrations.AlterUniqueTogether(
            name='routerate',
            unique_together={('route', 'supplier')},
        ),
        migrations.RenameModel(
            old_name='ProductVariety',
            new_name='Supplier',
        ),
        migrations.CreateModel(
            name='CrateDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('crates_given', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
            options={
                'unique_together': {('route', 'supplier', 'product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BusinessPointRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businesspoint')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
            options={
                'unique_together': {('business_point', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='BusinessPointDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('business_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businesspoint')),
            ],
            options={
                'unique_together': {('business_point', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BusinessPointCrateDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('crates_given', models.IntegerField(default=0)),
                ('business_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.businesspoint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
            options={
                'unique_together': {('business_point', 'supplier', 'product', 'date')},
            },
        ),
    ]
