# Generated by Django 4.2.14 on 2025-10-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesspoint_rename_variety_product_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='agent_name',
        ),
    ]
