# Generated by Django 4.2.14 on 2025-10-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_route_agent_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businesspointrate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='routerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businesspointrate',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AddField(
            model_name='routerate',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
        migrations.AlterUniqueTogether(
            name='businesspointrate',
            unique_together={('business_point', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='routerate',
            unique_together={('route', 'product')},
        ),
        migrations.RemoveField(
            model_name='businesspointrate',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='routerate',
            name='supplier',
        ),
    ]
