# Generated by Django 4.2.14 on 2025-10-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_businesspointrate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspoint',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='businesspoint',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
